"""initial migrate

Revision ID: 062c7c986349
Revises: 92a471f03955
Create Date: 2026-08-22 21:48:45.660489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062c7c986349'
down_revision = '92a471f03955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
