"""initial migrate

Revision ID: 0bfedd41bef7
Revises: a5024b4b330e
Create Date: 2026-08-21 20:44:02.982275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bfedd41bef7'
down_revision = 'a5024b4b330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('GENERAL', 'ATTENDANCE', 'EXCUSE', 'RESULT', 'EXAM', 'TIMETABLE', 'PROMOTION', 'SCHOOL_FEES', 'SYSTEM', name='notificationtype', create_type=False), nullable=False), sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recepient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_type', postgresql.ENUM('GENERAL', 'ATTENDANCE', 'EXCUSE', 'RESULT', 'EXAM', 'TIMETABLE', 'PROMOTION', 'SCHOOL_FEES', 'SYSTEM', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recepient_id'], ['users.id'], name=op.f('notification_recepient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.drop_table('notifications')
    # ### end Alembic commands ###
