"""update table

Revision ID: 543830281031
Revises: 1f6bc32626c9
Create Date: 2026-08-20 14:21:57.194028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '543830281031'
down_revision = '1f6bc32626c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_guardian_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_guardian_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', 'OTHER', name='parentguardianenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_guardian_id'], ['parentguardians.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_guardian_id'),
    sa.UniqueConstraint('student_id')
    )
    with op.batch_alter_table('parentguardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parentguardians', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    op.drop_table('parent_guardian_students')
    # ### end Alembic commands ###