"""update tables

Revision ID: a235531a7c87
Revises: 543830281031
Create Date: 2026-08-20 16:02:54.394709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a235531a7c87'
down_revision = '543830281031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_guardian_students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('parent_guardian_students_student_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_guardian_students', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('parent_guardian_students_student_id_key'), ['student_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
