"""init migrate

Revision ID: aa1469d71b53
Revises: f07a271f2650
Create Date: 2026-08-21 09:47:55.656532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1469d71b53'
down_revision = 'f07a271f2650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('teacher_permissions_teacher_id_permission_key'), type_='unique')
        batch_op.create_unique_constraint('uq_teacher_permission', ['teacher_id', 'permission'])
        batch_op.drop_constraint(batch_op.f('teacher_permissions_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_permissions_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'])
        batch_op.drop_constraint('uq_teacher_permission', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('teacher_permissions_teacher_id_permission_key'), ['teacher_id', 'permission'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
