"""add is_active to academic_sessions

Revision ID: ac9459ad90ce
Revises: 5aa5f626a51d
Create Date: 2026-08-15 17:32:51.298789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9459ad90ce'
down_revision = '5aa5f626a51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
