"""initial codes and table

Revision ID: f07a271f2650
Revises: a235531a7c87
Create Date: 2026-08-21 09:20:46.328076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07a271f2650'
down_revision = 'a235531a7c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('MARK_ATTENDANCE', 'ENTER_GRADES', 'UPDATE_GRADES', 'VIEW_TIMETABLE', 'VIEW_RESULTS', 'MANAGE_TEACHERS', name='permission'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'permission')
    )
    with op.batch_alter_table('parent_guardian_students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('parent_guardian_students_parent_guardian_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_guardian_students', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('parent_guardian_students_parent_guardian_id_key'), ['parent_guardian_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('teacher_permissions')
    # ### end Alembic commands ###
