"""added start date to term

Revision ID: f5ad0ea65959
Revises: 5c9a776d712f
Create Date: 2026-08-16 14:00:55.176376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ad0ea65959'
down_revision = '5c9a776d712f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.alter_column('academic_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.alter_column('academic_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
