from enum import Enum

class AuditAction(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    PASSWORD_RESET = "PASSWORD_RESET"
    PERMISSION_CHANGE = "PERMISSION_CHANGE"
    ACCESS_DENIED = "ACCESS_DENIED"
    EXPORT = "EXPORT"
    BULK_ACTION = "BULK_ACTION"
    VIEW = "VIEW"